### PR TITLE
Fixed camera handle setup

### PR DESCRIPTION
**Pull request by AlexReedy**
Initial changes for Andor

### CODE REVIEW

**Comment by scizen9** [comment]
@AlexReedy if you undo the changes to the config files, I will merge this.  The items in the config files should stay local during development and only become canonical after we deploy.  The changes to the logging, for example could disrupt the working system.

**Comment by AlexReedy** [comment]
Hey Don, I'm not sure exactly what you mean. I added the camera handle as
ifu handle = 100. Are you saying to not hardcode that? Also changes to
logging in the loggin.json file or how it handles logging in the andor.py
controller?

Thanks!
-Alex

**Comment by AlexReedy** [comment]
Reverted Configs back to original

**Comment by scizen9** [comment]
You still have the local IP for sedm.json.  Please remove any and all config files from the PR.  If this were merged, it would break the production system.

**Comment by AlexReedy** [comment]
Reverted rc_ip in sedm.json

**Pull request merged**
